Confluence storage and document plugin
Netflix/dispatch pull request #2940
Opened 2023-02-03 10:33 UTC by Cinojose

An attempt to create a confluence plugin for both storage and document. 

The plugin right now supports only cloud hosted confluence and can be extended down the road. Logs and sheets are not supported as confluence has no such concept. it make use of the _atlassian-python-api_ for the confluence api calls. 

I can create some screenshots on how it looks like, if there is a need. Please review.

2023-02-06 19:12 UTC, mvilanova requested changes
Looks good so far. Just minor stuff. I think there's an opportunity to have all the atlassian-related plugins (Jira and Confluence) under the same directory now and have all of them leverage (and extend if necessary) the config stuff such as HostingType and API related things. We could tackle it in a separate PR.

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"{drive_id} {name} {participants} {file_type}")
```suggestion
```

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while creating page: {e}")
Let's use our logger instead. Example here: https://github.com/Netflix/dispatch/blob/4e8ad0b48857f1bc78122a58b1365ff1d6687a01/src/dispatch/common/utils/cli.py#L9

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def copy_file(self, folder_id: str, file_id: str, name: str):
Missing typing

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Copy_file function with args {folder_id}, {file_id}, {name}")
Remove or use logger.

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while creating page: {e}")
Use logger.

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def move_file(self, new_folder_id, file_id, **kwargs):
Missing typing.

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def move_file_confluence(self, page_id_to_move, parent_id):
Missing typing.

2023-02-06 19:12 UTC, mvilanova commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while moving page: {e}")
Use logger.

2023-02-07 07:45 UTC, Cinojose commented on setup.py
> +            "dispatch_confluence_document = dispatch.plugins.dispatch_confluence.docs.plugin:ConfluencePageDocPlugin",
Done

2023-02-07 07:45 UTC, Cinojose commented on src/dispatch/incident/flows.py
> +        if sheet:
Done

2023-02-07 07:46 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/config.py
> +    """Type of Confluence deployment."""
Done

2023-02-07 07:46 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/config.py
> +    """Confluene configuration description."""
Done

2023-02-07 07:47 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    """Confluene configuration description."""
Done

2023-02-07 07:48 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Copy_file function with args {folder_id}, {file_id}, {name}")
Updated to logger.

2023-02-07 07:48 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while creating page: {e}")
Done

2023-02-07 07:49 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def move_file(self, new_folder_id, file_id, **kwargs):
Done

2023-02-07 07:49 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def move_file_confluence(self, page_id_to_move, parent_id):
Updated.

2023-02-07 07:50 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while moving page: {e}")
Updated.

2023-02-07 07:52 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    def copy_file(self, folder_id: str, file_id: str, name: str):
Fixed.

2023-02-07 07:52 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"Exception happened while creating page: {e}")
Fixed.

2023-02-07 07:52 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +            print(f"{drive_id} {name} {participants} {file_type}")
Removed.

2023-02-07 07:55 UTC, Cinojose commented on src/dispatch/plugins/dispatch_confluence/plugin.py
> +    description = "Conflunce plugin to create Incident documents"
Updated.

2023-02-07 17:35 UTC, mvilanova commented
Thanks for the PR!

2023-02-07 17:36 UTC, merged