MS teams conference initial commit
Netflix/dispatch pull request #3474
Opened 2023-06-07 04:38 UTC by Cinojose

Microsoft Teams Conference plugin.

Plugin to create Microsoft teams meetings during the incident creation. Plugin is tested as a part of the internal usage.
![Screenshot 2023-06-07 at 12 32 21 PM](https://github.com/Netflix/dispatch/assets/1662390/b517a940-7a4c-43c2-84a8-4d9bbbd2f293)

2023-06-07 22:54 UTC, mvilanova requested changes
Looks good! Thanks for the PR

2023-06-07 22:54 UTC, mvilanova commented on setup.py
> +            "teams_conference = dispatch.plugins.dispatch_microsoft_teams.conference.plugin:TeamsConferencePlugin",
nit: should we prefix with the company name, like we do for other plugins?
```suggestion
            "microsoft_teams_conference = dispatch.plugins.dispatch_microsoft_teams.conference.plugin:MicrosoftTeamsConferencePlugin",
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/config.py
> +        title="Azure Client Secret", description="This is the client secret created via Azure AD"
```suggestion
        title="Azure Client Secret", description="This is the client secret created via Azure AD."
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/plugin.py
> +    title = "Microsoft teams Plugin - Conference Management"
```suggestion
    title = "Microsoft Teams Plugin - Conference Management"
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/plugin.py
> +            logger.error(f"There is an error in creatig meeting {e}")
```suggestion
            logger.error(f"There was an error when attempting to create the meeting {e}")
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/plugin.py
> +    slug = "teams-conference"
```suggestion
    slug = "microsoft-teams-conference"
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/plugin.py
> +class TeamsConferencePlugin(ConferencePlugin):
```suggestion
class MicrosoftTeamsConferencePlugin(ConferencePlugin):
```

2023-06-07 22:54 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/config.py
> +class TeamsConfiguration(BaseConfigurationModel):
```suggestion
class MicrosoftTeamsConfiguration(BaseConfigurationModel):
```

2023-06-09 04:34 UTC, Cinojose commented
Fixed all the pr comments, please review. Thanks!

2023-06-12 18:14 UTC, mvilanova approved these changes

2023-06-12 18:14 UTC, mvilanova commented on src/dispatch/plugins/dispatch_microsoft_teams/conference/client.py
> +            return dict()
nit
```suggestion

        return dict()
```

2023-06-15 02:55 UTC, Cinojose commented
> @Cinojose can you fix the linting errors? https://github.com/Netflix/dispatch/actions/runs/5262948502/jobs/9528851603?pr=3474

Done, please check.

2023-06-20 18:24 UTC, merged