Putting a cap on the number of threads a scheduler can create
Netflix/dispatch pull request #3669
Opened 2023-08-07 20:18 UTC by kevgliss

2023-08-07 21:08 UTC, wssheldon approved these changes

2023-08-07 22:35 UTC, forestmonster requested changes
I'm curious about `concurrent.futures.ThreadPoolExecutor`, and if `num_workers=100` has the potential to create a new bottleneck?

2023-08-07 22:35 UTC, forestmonster commented on src/dispatch/scheduler.py
> +from multiprocessing.pool import ThreadPool
Without getting too deep here, you prefer this over `concurrent.futures.ThreadPoolExecutor`?

2023-08-07 22:35 UTC, forestmonster commented on src/dispatch/scheduler.py
> +    def __init__(self, num_workers=100):
Due to my lack of familiarity here... how does this not create a new bottleneck?

2023-08-08 20:30 UTC, forestmonster approved these changes

2023-08-08 20:30 UTC, merged