Send email to oncall when form is completed
Netflix/dispatch pull request #4264
Opened 2024-01-20 00:38 UTC by whitdog47

In this PR, an additional field for oncall service is added to the form type. When a form of this form type is submitted, if provided, the current oncall will receive an email notification about the completed form.

2024-01-21 18:07 UTC, anukaal approved these changes

2024-01-22 21:54 UTC, metroid-samus commented on src/dispatch/incident/messaging.py
> +        log.warning("Completed form notification email not sent, not email plugin configured.")
```suggestion
        log.warning("Completed form notification email not sent. No email plugin configured.")
```

2024-01-22 21:56 UTC, metroid-samus commented on src/dispatch/messaging/strings.py
> + submitted that requires your immediate attention. This form details
```suggestion
        submitted and requires your immediate attention. This form details
```

2024-01-22 22:11 UTC, metroid-samus commented on src/dispatch/static/dispatch/src/forms/types/NewEditSheet.vue
> +                <service-select label="Oncall Service" :project="project" v-model="service" />
This should be an optional field.

2024-01-22 22:16 UTC, metroid-samus commented on src/dispatch/forms/type/service.py
> +    service = service_service.get(
This field should be optional.

2024-01-22 22:19 UTC, metroid-samus approved these changes

2024-01-22 22:24 UTC, metroid-samus requested changes
Requesting changes

2024-01-22 23:10 UTC, metroid-samus approved these changes

2024-01-23 21:33 UTC, merged