Adding linting to migrations
Netflix/dispatch pull request #4874
Opened 2024-06-24 21:59 UTC by kevgliss

2024-06-24 22:04 UTC, wssheldon commented on .github/workflows/lint-migrations.yml
> +        uses: actions/setup-python@v2
```suggestion
        uses: actions/setup-python@v5
```

Is the latest version

2024-06-24 22:05 UTC, wssheldon commented on .github/workflows/lint-migrations.yml
> +      - uses: actions/cache@v2
```suggestion
      - uses: actions/cache@v4
```

Latest

2024-06-26 01:03 UTC, whitdog47 requested changes

2024-06-26 01:03 UTC, whitdog47 commented on src/dispatch/cli.py
> +    path = None
It looks like the playwright tests are failing since the `path` is still `None` and line `set_main_option` in line 418 requires a string.

2024-07-24 20:12 UTC, metroid-samus commented on src/dispatch/cli.py
> +    alembic_cfg.set_main_option("script_location", path)
```suggestion
        alembic_cfg.set_main_option("script_location", path)

2024-09-19 00:09 UTC, closed without merging